version: "3"

services:
  jupytex:
    build: devenv/.
    environment:
      SHELL: "/bin/bash"
      HOME: "/home/jupytex"
    tty: true
    command: bash -c "sleep infinity && jupyter lab --ip=0.0.0.0 --port=8000 --allow-root --no-browser"
    volumes:
      - ../:/home/jupytex
    ports:
      - "8000:8000"
