version: "3"

services:
  jupytex:
    #build: devenv/.
    build: .
    environment:
      SHELL: "/bin/bash"
      HOME: "/home/jupytex"
    tty: true
    command: bash -c "sleep infinity && jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''"
    volumes:
      - userspace:/home/jupytex
      - ../share_file:/home/jupytex/workspace/share
    ports:
      - "8888:8888"
  
volumes:
    userspace:
