version: "3"

services:
  jupytex:
    build: devenv/.
    #build: .
    environment:
      SHELL: "/bin/bash"
      HOME: "/home/jupytex"
    tty: true
    command: bash -c "sleep infinity && jupyter lab --ip=0.0.0.0 --port=8000 --allow-root --no-browser"
    volumes:
      - workspace:/home/jupytex
    ports:
      - "8000:8000"
  
volumes:
    workspace:
